version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      # - 8000:8000
    depends_on:
      - react-app-1
      - react-app-backend

  react-app-1:
    build: selq-client # image: selq-client:latest
    container_name: react-app-1
    env_file:
      - ./selq-client/.env
    expose:
      - 3000
    # ports:
    #   - 3000:3000

  react-app-backend:
    build: selq-server
    volumes:
      - ./selq-server:/usr/src/app
    env_file:
      - ./selq-server/.env
    command: npm run start:dev
    expose:
      - 8000
    # ports:
    #   - 8000:8000
