name: Docker CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx # Nginx Dockerfile이 있는 디렉토리 경로
          push: true
          tags: osdoonhyun/nginx:latest

      - name: Build and push Client
        uses: docker/build-push-action@v2
        with:
          context: ./selq-client # Client Dockerfile이 있는 디렉토리 경로
          push: true
          tags: osdoonhyun/client:latest

      - name: Build and push Server
        uses: docker/build-push-action@v2
        with:
          context: ./selq-server # Server Dockerfile이 있는 디렉토리 경로
          push: true
          tags: osdoonhyun/server:latest
