name: test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: ssh to ec2 
        uses: appleboy/ssh-action@master 
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          host: ${{ secrets.EC2_HOST }} 
          username: ${{ secrets.EC2_USERNAME }} 
          password: ${{ secrets.EC2_PASSWORD}}
          script: | # 실행 할 코드
            cd Sel-Q
            git pull https://osdoonhyun:${{ secrets.GIT_TOKEN }}@github.com/osdoonhyun/SEL-Q.git
